[versions]
ext-java = "21"
ext-minecraft-current = "1.21.1"
ext-minecraft-range = "[1.21.1, 1.22)"
ext-neo-form = "1.21.1-20240808.144430"
ext-fabric-api = "0.109.0+1.21.1"
ext-fabric-loader = "0.16.9"
ext-neoforge-api = "21.1.80"
ext-neoforge-loader-range = "[4,)"
ext-plugin-fabric-loom = "1.8.13"
ext-plugin-neoforge-moddev = "2.0.141"
ext-library-mixin = "0.8.5"
ext-library-mixinextras = "0.3.5"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "ext-minecraft-current" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "ext-fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "ext-fabric-api" }
mixin-core = { module = "org.spongepowered:mixin", version.ref = "ext-library-mixin" }
mixinextras = { module = "io.github.llamalad7:mixinextras-common", version.ref = "ext-library-mixinextras" }
fabric-loom-gradle-plugin = { module = "net.fabricmc:fabric-loom", version.ref = "ext-plugin-fabric-loom" }
neoforge-moddev-gradle-plugin = { module = "net.neoforged:moddev-gradle", version.ref = "ext-plugin-neoforge-moddev" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "ext-plugin-fabric-loom" }
neoforge-moddev = { id = "net.neoforged.moddev", version.ref = "ext-plugin-neoforge-moddev" }
